dead_space_chain:
  chainId: 0xD5C0
  chainName: Dead Space Chain
  rpcUrls:
    - https://rpc.deadspace.invalid
  explorer: https://explorer.deadspace.invalid
addresses:
  merkleDistributorDeadSpace: 0xMerkleDistributorOnDeadSpace
  lockboxL2: 0xDeadLockbox
l1:
  merkleDistributorL1: 0xMerkleDistributorOnEthereum
  lockboxL1: 0xL1Lockbox
  wdead: 0xWDEAD
proofBaseUrl: /epoch/current
challengeSeconds: 3600
