version: "3.8"
services:
  bootnode:
    image: ethereum/client-go:stable
    command: ["--http","--http.addr","0.0.0.0","--http.api","eth,net,web3","--http.vhosts","*","--http.corsdomain","*","--dev"]
    ports:
      - "8545:8545"
      - "8546:8546"
    restart: unless-stopped
